### ISSUE TITLE
Project compatible environment

### ISSUE THREAD

**Issue by wpoortman** [paliarush/vagrant-magento#111]
I've been working on a solution to make things work with for instance Github or Bitbucket repositories. Finally I decided to post this request, after working on it for several days trying to fix all problems I've came across.

Is it possible to add some kind of 'project environment' where you can insert Bitbucket repo url's instead of just only CE or EE repo's. Yes, if you just replace the CE or EE url with a git url... it kinds of work but it always requires a complete Magento instance instead of just project code with a composer file to install Magento afterwards.

I can show you some of the work I've already did... but it not really robust and would be awesome to just have it inside of the project.

You can always contact me!

**Comment by paliarush** [comment]
@wpoortman Please commit anything you have at this point to your fork. Also provide step-by-step requirements with URLs to source code of project you are trying to install. As far as I understand so far, you are trying to install a project, which has Magento as a dependency in composer.json, correct?
Thank you for your interest in this project.
