### ISSUE TITLE
ssh-agent problem

### ISSUE THREAD

**Issue by TapaniAla** [paliarush/vagrant-magento#114]
When running bash init_project.sh I got several error messages like this:
"The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.
If the problem persists, please report a bug to the net-ssh project."
I fixed this issue by removing all keys from ~/.ssh/. Is there a better way to handle this problem with conflict of vagrant ssh and other ssh users like github? I saw some complicated solutions when searching this issue.

**Comment by paliarush** [comment]
Not sure what your host is, but I have tested current project on Ubuntu 14.04, OSX 10.11 and Windows 10, and have never seen such issues. 

To avoid using ssh keys, you can specify repository URLs in `etc/config.yaml` in https format. See http://stackoverflow.com/questions/5343068/is-there-a-way-to-skip-password-typing-when-using-https-on-github , which describes how to authenticate in this case.

Probably it is better to ask your question on http://stackoverflow.com.

**Comment by TapaniAla** [comment]
Thanks, 
This is actually the same error message as in issue #76 but different origin. In my case I have OSX 10.11. 
Stackoverflow has many proposals how to solve this problem. The one I already used was the simplest one. Your script is  the most complete and versatile vagrant-magento script I have found so far. I believe it's really hard to make universal script for this environment.
