### ISSUE TITLE
No write permissions for /pub/media and /pub/static

### ISSUE THREAD

**Issue by PivitParkour94** [paliarush/vagrant-magento#119]
I tried to delete the media and static folders after a `setup:upgrade` and got 

```

  [Exception]
  Missing write permissions to the following paths:
  /var/www/magento2ce/pub/media
  /var/www/magento2ce/pub/static

```
I just assumed that in the setting up of all the folder permissions (like `magento2ce/var`) the `pub/media` and `pub/static` would also be added to that user group.

Is it intentionally not added for some reason? I found I could `sudo rm -rf pub/media` and that worked fine to remove the folders.

**Comment by paliarush** [comment]
When this box is installed on Window hosts, ownership of the whole Magento directory should be `vagrant:vagrant`. Apache is running under `vagrant` user so all files created by Magento should have the same owner.

If you could provide mode details (steps to reproduce), I will try to fix it.

**Comment by PivitParkour94** [comment]
I did fix it temporarilly by using `chown vagrant:vagrant pub/static pub/media` and I noticed that this is in the provissioning of the Vagrant box, but for some reason it didn't work. I'll play around a bit more. 
Thanks

**Comment by paliarush** [comment]
Feel free to reopen the issue if you have more details. Thanks
