### ISSUE TITLE
Why isn't the entire project folder being synced on Windows?

### ISSUE THREAD

**Issue by jasonheecs** [paliarush/vagrant-magento#122]
Hi,

What is the [rationale behind only syncing](https://github.com/paliarush/magento2-vagrant-for-developers/blob/e97c83a2e9258f38ca9c3bee69e33904474ca650/Vagrantfile#L62-L64) the '/var' and '/app/etc' directories on Windows?

**Comment by paliarush** [comment]
Hi, please see https://github.com/paliarush/magento2-vagrant-for-developers/blob/2.0/docs/performance-issue-on-windows-hosts.md
