### ISSUE TITLE
Fail to check mounted directories

### ISSUE THREAD

**Issue by samuelecarpene** [paliarush/vagrant-magento#123]
when i execute 
`bash init_project.sh`
the execution terminate in the file
`scripts/host/check_mounted_directories.sh`
line 9.

What can i do to solve the problem?
I'm on
- windows 10
- virtual box 5.1.14
- vagrant 1.9.1
- git 2.11.0

**Comment by paliarush** [comment]
Looks like Vagrant cannot mount shared folders on your instance. Try simple vagrant configuration similar to the one mentioned in https://github.com/paliarush/magento2-vagrant-for-developers/issues/88, but without NFS option. Please let me know the results.
