### ISSUE TITLE
Magerun compatibility

### ISSUE THREAD

**Issue by tmos** [paliarush/vagrant-magento#125]
Hi,

Is there any way to make [Magerun](http://magerun.net/) works with the Vagrant image ?
If I install Magerun on my host system (OSX), and just launch a command, it says :

```
[CredisException]
  Connection to Redis failed after 2 failures.Last Error : (61) Connection refused
```

Thanks for any help !

**Comment by wrock** [comment]
Guten Tag, 

Vielen Dank für Ihre Nachricht. Ich bin bis 12.2.2017 auf Urlaub. 
In dringenden Fällen erreichen Sie meinen Kollegen Herrn Krieger  unter web@rockit.at.

Mit freundlichen Grüßen, 
Wolfgang Rock

**Comment by paliarush** [comment]
@tmos Redis and other tools are installed on virtual machine. I have not used Magerun so not sure about its requirements. 

Please try to install Magerun on the guest machine (use 'vagrant ssh' to get inside).
