### ISSUE TITLE
Composer Dependencies not met by local system

### ISSUE THREAD

**Issue by henryhardy** [paliarush/vagrant-magento#126]
I'm not sure if this is more of a vagrant/composer issue than a repo issue, but say I want to add a composer dependency to my magento install. 

I run for example 

    composer require yukoff/magento2-sendgrid-smtp

while in the magento directory (not the project root)

It throws an error about needing x php module installed, but I already know this module is installed on the vagrant box. Is there a way that I should be adding the dependency to the composer.json file, but not install it until it gets into the vagrant box?

Thanks!

**Comment by paliarush** [comment]
Just use `--ignore-platform-reqs` option while using composer, it will ignore PHP requirements then.
