### ISSUE TITLE
Where do Magento errors log?

### ISSUE THREAD

**Issue by jwineman** [paliarush/vagrant-magento#130]
Sorry I know this is a dumb question but I can't find the Magento error log for this Vagrant box.  Any pointers on where to look?

**Comment by TapaniAla** [comment]
Should be under /var/www/magento2ce/var/log/ in guest and in /magento2ce/var/log/ in host. System logs are in /var/log/ in guest.

**Comment by paliarush** [comment]
The whole `magento2ce/var` directory on the host should be synchronized with `magento2ce/var` directory on the guest.  So on both OSX and WIndows hosts logs can be found under `magento2ce/var/log`.

**Comment by jwineman** [comment]
Thanks - that was my assumption.  Needed a sanity check.
