### ISSUE TITLE
fatal error when trying to install sample data

### ISSUE THREAD

**Issue by GerardKetuma** [paliarush/vagrant-magento#132]
Setting the config option install_sample_data to 1 gives a fatal error in CE after I run m-switch-to-ce -f. Then I reran install script init_project.sh -fc but still get the same error.

`Fatal error: Uncaught Magento\Framework\Exception\LocalizedException: Invalid Document Element 'type', attribute 'name': [facet 'pattern'] The value '\Magento\Framework\Mail\TransportInterface' is not accepted by the pattern '([a-zA-Z_-ÿ][a-zA-Z0-9_-ÿ]*)(\\[a-zA-Z_-ÿ][a-zA-Z0-9_-ÿ]*)*'. Line: 9 Element 'type', attribute 'name': '\Magento\Framework\Mail\TransportInterface' is not a valid value of the atomic type 'phpClassName'. Line: 9 Element 'type', attribute 'name': Warning: No precomputed value available, the value was either invalid or something strange happend. Line: 9 in /Volumes/Vagrant/magento_projects/vagrant-magento/magento2ce/lib/internal/Magento/Framework/Config/Reader/Filesystem.php on line 160`

**Comment by paliarush** [comment]
It is possible that you are using incompatible versions of sample data and Magento (branch names should be the same).

This error is caused by one of the latest accepted PRs to the Magento dev branch https://github.com/magento/magento2/pull/8743 and is not related to current vagrant box.
Please report the issue there.

**Comment by GerardKetuma** [comment]
@paliarush Yes I finally resolved the issue by specifying the release (::2.1) and also same thing for the sample data in the config.yml file. Running it without specifying a release gets a dev branch of Magento CE and there wasn't any corresponding sample data.
Maybe an improvement will be to set a release for both Magento CE and sample data as a default which will help resolve this issue for others.

**Comment by paliarush** [comment]
@GerardKetuma Could you please provide the git section of the config which was causing the problem for you? 
All branches should contain code related to the same Magento version, e.g. develop/2.1/2.0
