### ISSUE TITLE
Question: Stop and start the virtual machine

### ISSUE THREAD

**Issue by andertun** [paliarush/vagrant-magento#134]
I'm new to vagrant and magento, so this is probably a quite simple thing.

When I stop the virtual machine with `vagrant halt`, and later start it again with `vagrant up` I can't access the store.

Is there a script I should run instead, that mounts everything correctly, or how do you start and stop?

**Comment by paliarush** [comment]
@andertun It should work in the scenario you described. Please try `vagrant reload`, since it helps in most of cases when something does not work.
If the issue persists, please provide more details about your environment: such as host OS, vagrant version, virtual box version etc.

**Comment by ricardowong** [comment]
Although not a solution, I would prefer **vagrant suspend** as oposed to vagrant halt. That is, if your goal is just to pause and continue later.
