### ISSUE TITLE
Update path to Code Sniffer rules for Magneto 2.2

### ISSUE THREAD

**Issue by paliarush** [paliarush/vagrant-magento#135]
The path to code sniffer rules in Magento 2.2 was changed from `dev/tests/static/testsuite/Magento/Test/Php/_files/phpcs/ruleset.xml` to `dev/tests/static/framework/Magento/ruleset.xml`. The latter one also exists in 2.0 and 2.1, but is not complete. The easiest solution for now would be to use `dev/tests/static/framework/Magento/ruleset.xml` in all Magento versions.

**Comment by eric-bohanon** [comment]
https://github.com/paliarush/magento2-vagrant-for-developers/pull/136 resolves this issue

**Comment by paliarush** [comment]
#136 fixes the issue for new installations (or after `init_project.sh -fp` is used). 

Existing installations may still be affected by this issue. It be solved by updating to the latest version of this project and running `init_project.sh -fp` in the root.
