### ISSUE TITLE
Installing missing vagrant plugins [init_project.sh] - stdout is not a tty

### ISSUE THREAD

**Issue by gabarba** [paliarush/vagrant-magento#143]
Hi, 
I am trying to run the init_project.sh script that comes along with the repo I am using Git-Bash like it has been suggested but I keep coming up with the following error shortly after it starts. 

```
[2017-08-22 15:29:38] Installing missing vagrant plugins [init_project.sh]
stdout is not a tty
```

I've been trying to troubleshoot the error with varing degrees of success but nothing being able to fully complete the install process.  

I have been fiddling around with reinstalling git for windows in various configurations as suggested online but non seem to have solved the problem. 

It looks like the following line is the culprit
```
vagrant_plugin_list="$(vagrant plugin list)"
```
and I have threw in a string just to continue the script and install the required plugins and gotten the script to continue to again shoot out the error in other places anyways.

Instead of banging my head on this issue I'm hoping that you guys will have a quick answer and will know what the problem might be. 

I am running windows 10 64 bit. I have php 7 and composer installed tested working.  Vagrant and Virtual box are installed as well and I have manually verified that the plugins are installed. 

Thanks again for any help on this matter,

George B.

**Comment by paliarush** [comment]
@gabarba please try to use different version of Git-Bash or Cygwin. I've never seen this problem before. I cannot test it right now because I don't have access to Windows machine.

**Comment by fleveque** [comment]
I tried it today and I faced the same error (w10, php7), and managed to skip the issue changing the line:

`vagrant_plugin_list="$(vagrant plugin list)"`

to:

`vagrant_plugin_list=(echo "vagrant plugin list")`

But I have similar issues on filterVagrantOutput() function of output_functions.sh file.

**Comment by paliarush** [comment]
I have just tried installing the project with default config.yaml (it is automatically created out of config.yaml.dist) on Windows 10 and everything worked for me. I have VirtualBox 5.1.3 there, git 2.9.3.windows1, Vagrant 1.8.5

Please try installing same versions of required software, or provide me your versions so I can try to reproduce the issue. Thanks
