### ISSUE TITLE
Sample data from magento or custom?

### ISSUE THREAD

**Issue by lfolco** [paliarush/vagrant-magento#148]
When I follow the instructions to install sample data, it is only generating the lightweight sample data (#102). Is it possible to use the Magento sample data?

In config.yaml, I have the following custom settings:

```
checkout_source_from: "composer"
install_sample_data: 1
```

I also have this for sample data (default value):

```
ce_sample_data: "git@github.com:magento/magento2-sample-data.git"
```

**Comment by paliarush** [comment]
Git version of sample data is used only when you install Magento from Git. 

When Magento is installed via Composer, please follow http://devdocs.magento.com/guides/v2.1/install-gde/install/sample-data-after-composer.html to install sample data
