### ISSUE TITLE
Could I use the magento2ce to be my local machine?

### ISSUE THREAD

**Issue by tshuy** [paliarush/vagrant-magento#154]
How do I migrate my production server to your magento2ce folder?  Then I can use it as my local machine.
If this is the case then I will use this local machine to develop additional enhancements.  make sure it works, then move it to the production server.

**Comment by paliarush** [comment]
Hi @tshuy, ideally you should use some staging server with the same configuration as your production.

Just download your codebase and put it to 'magento2ce' directory before running ./init_project.sh. 

Then ./init_project.sh will create Magento instance using the code provided in 'magento2ce'.
