### ISSUE TITLE
check_mounted_directories.sh looking for file that doesn't exist

### ISSUE THREAD

**Issue by ts-hww** [paliarush/vagrant-magento#163]
I am getting this error message when running init_project.sh:

"Directory '${vagrant_dir}/etc' was not mounted as expected by Vagrant. Please make sure that 'paliarush/magento2.ubuntu' Vagrant box was downloaded successfully (if not, this may help http://stackoverflow.com/questions/35519389/vagrant-cannot-find-box) And that Vagrant is able to mount VirtualBox shared folders on your environment (see https://www.vagrantup.com/docs/synced-folders/basic_usage.html )"

I'm confused on how to resolve it because the condition in check_mounted_directories.sh is [[ ! -f "${vagrant_dir}/etc/guest/mysql/my.cnf" ]] but I don't see mysql/my.cnf in the repo. 

Am I missing something? Windows 10 - Vagrant 1.8.5 - VirtualBox 5.1.3

**Comment by ts-hww** [comment]
I solved it. Git config autocrlf was true, so checking out code was adding a carriage returns to scripts which messed things up.

**Comment by jordangottlieb-ych** [comment]
So you got this box to work on windows 10? Did you try to switch to EE? Are you using PhpStorm? Sigh.

**Comment by ts-hww** [comment]
Yeah, got it working on one Windows 10 PC, but not another. I installed PhpStorm and use that to deploy, as mentioned in the project docs. I did not try to switch to EE, although I did notice that the default config.yaml doesn't have the repo URL for EE.

Some things that may or may not have helped:

add Vagrant to PATH
add virtualbox to PATH
use these versions:  VirtualBox 5.1.3  Vagrant 1.8.5
remove plugins after downgrading vagrant.   rm -r ~/.vagrant.d/plugins.json ~/.vagrant.d/gems
run bash as administrator when running init_project.sh (this lets it make symlinks)
uncommented line about vb gui as specified in vagrantfile
installed NFS (shouldn't have made a difference).   vagrant plugin install vagrant-winnfsd
git config --global core.autocrlf = false   (clone and check out again after changing this)

My other Windows 10 PC that will not run it may be having trouble because of the processor, though I don't know. That would be the next thing I look into with that, whether or not vagrant or vb or whatever not being able to do a 64 bit virtual processor on a host with whatever certain type of processor or something.

Hope that helps.

**Comment by jordangottlieb-ych** [comment]
Thank you for the great info, every little bit helps!  While I have you on the line, do you see anything glaring here: [https://github.com/paliarush/magento2-vagrant-for-developers/issues/162](https://github.com/paliarush/magento2-vagrant-for-developers/issues/162) ? I can get this vagrant box up and running, but things go south quick when you try adding things on PhpStorm or switching to EE.
