### ISSUE TITLE
Magento installation failed.PHP Fatal error:  Cannot use Magento\Payment\Gateway\ConfigInterface as ConfigInterface because the name is already in use in /Users/matteofonsatti/Desktop/magento2/vagrant-magento/magento2ce/app/code/Magento/Payment/Model/Method/Logger.php on line 8

### ISSUE THREAD

**Issue by mfonsatti** [paliarush/vagrant-magento#175]

**Comment by e-solutions** [comment]
I am also getting this exact same error.

**Comment by mrtuvn** [comment]
You should checkout codebase from stable branch such as 2.2 instead development because some issue not fixed yet

**Comment by mfonsatti** [comment]
@mrtuvn thanks a lot , but i've made checkout from default branch that is the 2.0 version . There's no 2.2 branch .

**Comment by mfonsatti** [comment]
@mrtuvn do you mean to use a version 2.2 of Magento ?
the version of magento is in file https://github.com/paliarush/magento2-vagrant-for-developers/blob/2.0/etc/config.yaml.dist , is it right ? (just for clear for anyone ;-)

**Comment by mfonsatti** [comment]
it works !!! i've added in line 17 of etc/config.yaml the version 2.2 of magento so ...
  ce: "git@github.com:magento/magento2.git::2.2"
thanks a lot @mrtuvn !

**Comment by e-solutions** [comment]
It worked for me too. THANKS.  :-)

**Comment by mtkumar82** [comment]
Facing exact same issue in magento2.4, 
Fatal error: Cannot use Magento\Payment\Gateway\ConfigInterface as ConfigInterface because the name is already in use in D:\magento2_4\app\code\Magento\Payment\Model\Method\Logger.php on line 8

Any solution for this?

**Comment by purnagattu** [comment]
I'm also facing similar issue with 2.2.4 version "PHP Fatal error:  Cannot use Magento\Payment\Gateway\ConfigInterface as ConfigInterface because the name is already in use in C:\xampp\htdocs\dreamkart\vendor\magento\module-payment\Model\Method\Logger.php on line 8"

**Comment by Princep1619** [comment]
Fatal error: Cannot use Magento\Payment\Gateway\ConfigInterface as ConfigInterface because the name is already in use in C:\xampp\htdocs\magento\vendor\magento\module-payment\Model\Method\Logger.php on line 8
