### ISSUE TITLE
Add Magento Sample Data Support

### ISSUE THREAD

**Issue by paliarush** [paliarush/vagrant-magento#18]
It should be possible to specify sample data repository in [config.yaml](https://github.com/paliarush/magento2-vagrant-for-developers/blob/develop-phpstorm-settings/etc/config.yaml.dist). New script should be introduced (e.g. `m-reinstall-with-sample-data`) and it should  link sample data directories, invoke `m-reinstall` and then unlink sample data directories.

When you switch between CE and EE, or invoke `m-reinstall` there must be no sample data installed.

Fix must be backward compatible.

**Comment by spittfree** [comment]
Hi,

Any progress on the sample data?

Thanks,
Carles

**Comment by paliarush** [comment]
@spittfree Cannot guarantee, but may be done in a month or so. You are welcome to participate, current code is available in separate branch: https://github.com/paliarush/magento2-vagrant-for-developers/tree/Sample-Data-Support

**Comment by spittfree** [comment]
Will take a look, thanks

**Comment by paliarush** [comment]
Merged in scope of #72.

@spittfree feel free to checkout.
