### ISSUE TITLE
Does it install magento automatically? question

### ISSUE THREAD

**Issue by ClaudiuCreanga** [paliarush/vagrant-magento#19]
I don't understand why there is a config.yaml file. Does it run composer install automatically? If yes, I don't see why because most likely you are cloning an already existing project with a database and start making changes... Or am I wrong?

**Comment by paliarush** [comment]
[config.yaml](https://github.com/paliarush/magento2-vagrant-for-developers/blob/2.0/etc/config.yaml.dist) allows you to configure several things:
- git repository/repositories to be cloned. Options include 
  - https://github.com/magento/magento2 (default one)
  - https://github.com/magento/magento2-community-edition (to install Magento from composer packages)
  - core Magento developers use another, corporate repository
  - it is also possible to specify EE repository
- Network settings (IP, port, type of mounting between guest and host)
- Guest machine environment settings. PHP version is the only option for now, but the list of settings will be extended
- Options for Magento installation script (admin name, password, locale options etc)

So config.yaml does not have anything in common with Magento `composer.json`, which is used to pull Magento dependencies. 

And yes, everything will be cloned and installed automatically when you execute [init_project.sh](https://github.com/paliarush/magento2-vagrant-for-developers/blob/2.0/init_project.sh). See [installation steps](https://github.com/paliarush/magento2-vagrant-for-developers#installation-steps) for more details.

**Comment by ClaudiuCreanga** [comment]
Thanks for replying. Is there a possibility to use your setup to build a development environment for an already existing magento installation which is live? 
From what i understand running bash init_project.sh will install a clean version of magento.

**Comment by paliarush** [comment]
init_project.sh will install a clean version of Magento, that is correct. However, it should be possible to migrate your live DB to this environment after installation, try to search at http://magento.stackexchange.com how to do that.
