### ISSUE TITLE
Cygwin cygheap base mismatch detected

### ISSUE THREAD

**Issue by Alterna016** [paliarush/vagrant-magento#194]
Does someone know how to resolve this? I read online that it has to do with the path within the vbox to cygwin inside the sh script?
 
[main] tar (1172) C:\Program Files\Git\usr\bin\tar.exe: *** fatal error - cygheap base mismatch detected - 0x1802F6408/0x180318410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL

**Comment by justincormier** [comment]
I'm running into this problem, did you find a solution?

**Comment by createadrln** [comment]
Also an  issue
