### ISSUE TITLE
PHP Module does not exist

### ISSUE THREAD

**Issue by mrtuvn** [paliarush/vagrant-magento#227]
I try to re-init and re-create VM but it's not work
only php7.0 can work i can't make php 7.1 and php 7.2 work
Before it's work but currently it's not. My report at 2/6/2019
Can we get new vagrant image build come with 
ubuntu , composer higher version?

![vagrant-php](https://user-images.githubusercontent.com/1908873/58758836-bc515900-854b-11e9-93c3-f43daf99043e.PNG)

**Comment by JackWormUK** [comment]
Yes we Know, see issue 226.  Ubuntu 14 is EOL, so PHP has been removed from the repository

**Comment by mrtuvn** [comment]
thanks for your info. Seem we can't do anything here and have to wait update ubuntu image from @paliarush

**Comment by JackWormUK** [comment]
It looks like it.  You cant just do a straight upgrade from 14 to 16 unfortunately

**Comment by JackWormUK** [comment]
For reference i think @paliarush has perhaps moved on to Docker over Vagrant, so I will have a go at using the docker version.  [Docker Version Link](https://github.com/magento/magento2-kubernetes-devbox)
