### ISSUE TITLE
[Windows] m-switch-to-ee with 2gb might be failed during magento installation step

### ISSUE THREAD

**Issue by arkadiych** [paliarush/vagrant-magento#40]
Steps to reproduce:
1. Set memory to 2048.
2. Run m-switch-to-ee, wait while files are synchronized, press any key to resume magento installation process. 

Expected: Magento EE installed successfully.
Actual:  m-switch-to-ee fails with killed process. (not always reproducible)

Workaround: run "vagrant reload"

**Comment by paliarush** [comment]
@arkadiych Will you be able to fix this? I cannot reproduce it on OSX
