### ISSUE TITLE
scripts throw 'expected binary operator'

### ISSUE THREAD

**Issue by riconeitzel** [paliarush/vagrant-magento#42]

**Comment by paliarush** [comment]
@riconeitzel what host environment do you have? I have never seen this error

**Comment by riconeitzel** [comment]
OS X El Capitan, using ZSH

Best, Rico

**Comment by paliarush** [comment]
Ok, thanks, never tried that though. Everything worked fine in the native El Capitan terminal and PhpStorm terminal
