### ISSUE TITLE
Package fabpot/php-cs-fixer is abandoned

### ISSUE THREAD

**Issue by riconeitzel** [paliarush/vagrant-magento#46]
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.

**Comment by paliarush** [comment]
This is actually a dependency of Magento2, not of vagrant project (see https://github.com/magento/magento2/blob/develop/composer.lock#L3036). I assume it will be fixed soon.

**Comment by yuheng6336** [comment]
I am using Magento 2.0.5. When I run the composer update  command it's showing the following warning.
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friends ofphp/php-cs-fixer instead.
Writing lock file
can you help me?

**Comment by paliarush** [comment]
@yuheng6336 Just ignore this warning. It is a dependency of Magento 2 itself so I cannot fix it in vagrant project.
I expect it to be fixed in the nearest release of Magento 2.

**Comment by rahul-avion** [comment]
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.plz solution..?

**Comment by paliarush** [comment]
@rahul-avion why is this a problem for you? It is just a warning about Magento 2 dependencies. 
Is something do not work for you because of this warning?

**Comment by lojasmarques** [comment]
não é possível atualizar do Magento 2.1.6 para o 2.1.7 DEPOIS QUE INSERIR na pasta de instalação do Magento 2.1.6 depois de executar aparece um erro.
