### ISSUE TITLE
init-project.sh failing when in directory structure with spaces

### ISSUE THREAD

**Issue by riconeitzel** [paliarush/vagrant-magento#58]
Put you project into /Volumes/_/My Vagrant Machines/_ and let the init-project.sh run.

**Comment by paliarush** [comment]
Is blocked by https://github.com/mitchellh/vagrant/issues/7540

**Comment by paliarush** [comment]
Issue is fixed for Windows hosts and for Linux/OSX hosts in non-NFS mode. Should work in NFS mode when mitchellh/vagrant#7540 is resolved.
