### ISSUE TITLE
chmod: cannot access ‘bin/magento’: No such file or directory

### ISSUE THREAD

**Issue by CNSam** [paliarush/vagrant-magento#59]
Hi there,

During the installation (presumably at the part where it tries to install Magento) I am getting the following error:

```
+ sudo chmod +x bin/magento
chmod: cannot access ‘bin/magento’: No such file or directory
```

Please could you advise where im going wrong?

**Comment by paliarush** [comment]
@CNSam What is your host OS? If windows, then probably Magento codebase was not uploaded to the guest for some reason. Also please check FAQ section in readme, it is possible that you find answer there.

**Comment by bryfa** [comment]
I have the same issue here on a Windows 10 machine.
Is there a workaround/fix for this?

**Comment by paliarush** [comment]
Try logging in to the machine and do `chmod a+x` for the file which is mentioned in the error message.
