### ISSUE TITLE
php version 7.0.5

### ISSUE THREAD

**Issue by dlehren** [paliarush/vagrant-magento#60]
Hi,

On a fresh install i am getting the below error. 
"Magento supports PHP 5.6, 7.0.2, and 7.0.6 or later. Please read Magento System Requirements."

It seems like its installing a php version(7.0.5) thats not compatible with magento 2.1.0

Thanks.

**Comment by paliarush** [comment]
@dlehren Looks like you have old vagrant box. Try to run:
`vagrant box update` and then recreate project.

Also `vagrant reload` should help since there are scripts in place which upgrade environment for you. Just make sure that you have the latest code from 2.0 branch of current project.

**Comment by dlehren** [comment]
@paliarush 
Thanks that worked.
