### ISSUE TITLE
Add help documentation to configure phpunit in windows

### ISSUE THREAD

**Issue by jrosell** [paliarush/vagrant-magento#62]
I'm trying to configure phpunit in phpstorm and I get errors. I think it would be wonderful to have documentation on how to configure phpunit in windows.

Tried to follow:
- https://confluence.jetbrains.com/display/PhpStorm/Running+PHPUnit+tests+over+SSH+on+a+remote+server+with+PhpStorm
- http://devdocs.magento.com/guides/v2.0/test/unit/unit_test_execution_phpstorm.html

When I "play" phpunit, i get this:

> vagrant://C:\Users\Jordi\vagrant-magento/usr/bin/php /home/vagrant/.phpstorm_helpers/phpunit.php --configuration /vagrant/magento2ce/dev/tests/unit/phpunit.xml.dist
> Testing started at 10:58 ...
> bash: line 0: cd: /vagrant/magento2ce/dev/tests/unit: No such file or directory
> Could not read "/vagrant/magento2ce/dev/tests/unit/phpunit.xml.dist".

My configuration:

![screenshot 2016-06-30 11 08 36](https://cloud.githubusercontent.com/assets/1544992/16483085/1102f6c6-3eb3-11e6-990a-6a04cc3d2d5a.png)

![screenshot 2016-06-30 11 06 53](https://cloud.githubusercontent.com/assets/1544992/16483046/e9252b38-3eb2-11e6-829c-47e3ccdaac66.png)

**Comment by paliarush** [comment]
Steps I follow to run tests:
1. Make sure that remote PHP is selected as Interpreter (use Deployment configuration, not Vagrant configuration in Interpreters form)
2. Copy phpunit.xml.dist to phpunit.xml and make necessary changes
3. Limit scope to specific tests, e.g. `<directory suffix="Test.php">testsuite/Magento/Framework/MessageQueue/ConfigTest.php</directory>`
4. Right click on phpunit.xml and run

There were plans to create testing profiles automatically on project initialization in scope of #13
