### ISSUE TITLE
Cannot switch to EE

### ISSUE THREAD

**Issue by Jrb1x** [paliarush/vagrant-magento#64]
The config.yaml file shows the correct path to the magento2ee folder. Upon running:

`bash init_project.sh -c`

I still get the message that the EE codebase is not available.

**Comment by paliarush** [comment]
I don't think it is possible to use `-c` without `-f` (recreation of box), so please try `bash init_project.sh -fc`.

> The config.yaml file shows the correct path to the magento2ee folder.

I suppose you mean ee repository, not path.

Another way to add EE after project is already initialized - to manually checkout magento CE codebase to `vagrant_project/magento2ce` and checkout magento EE codebase to `vagrant_project/magento2ce/magento2ee`. Then just run `bash m-switch-to-ee`

**Comment by Jrb1x** [comment]
Thanks for the reply. Yes, I meant repository. I've got EE up on a private repo and I'm using the repository url in `config.yaml`.

I ran `bash init_project.sh -fc`and still no luck. I also tried checking the repo's out after initializing. Still no luck.

```
macbookpro-jb:vagrant-magento josh$ bash m-switch-to-ee
+ [[ -f /Users/josh/Documents/Projects/Magento/local/vagrant-magento/lib/php/php.exe ]]
+ php_executable=php
+ echo php
+ [[ ! -f /Users/josh/Documents/Projects/Magento/local/vagrant-magento/magento2ce/magento2ee/app/etc/aliases_to_classes_map.json ]]
+ set +x
EE codebase is not available
```

**Comment by Jrb1x** [comment]
It does attempt to clone the EE repo whenever resetting the environment, but it still doesn't see it after bringing the box up.

**Comment by paliarush** [comment]
@Jrb1x could you please share your `config.yaml`? 

Are you able to clone your repository using git protocol manually via command line without entering credentials? In such format
 `git clone git@github.com:paliarush/magento2-vagrant-for-developers.git .`

**Comment by paliarush** [comment]
@Jrb1x did you make it work?
