### ISSUE TITLE
install npm by default 

### ISSUE THREAD

**Issue by refaelgold** [paliarush/vagrant-magento#69]
i try to install npm and gulp at the vagrant machine but i get a lot of issues
there is any why to install it that you recommended?

thanks!

**Comment by paliarush** [comment]
Here is the list of steps provided by @riconeitzel when he was installing npm and grunt (not sure about gulp):

1.) git clone https://github.com/paliarush/magento2-vagrant-for-developers.git mage2_vagrant
2.) cd mage2_vagrant
3.) git clone https://github.com/magento/magento2.git magento2ce
4.) cd magento2ce
5.) git checkout 2.0
6.) ./init-project.sh
7.) git clone https://github.com/magento/magento2-sample-data sampledata
8.) vagrant ssh
9.) cd {magento_root}/sampledata
10.) php -f {magento_root}/sampledata/dev/tools/build-sample-data.php -- --ce-source="{magento_root}"
11.) cd ..
12.) rm -rf var/cache/ var/page_cache/ var/tmp/ var/generation/ var/view_preprocessed/
13.) bin/magento setup:upgrade
14.) bin/magento setup:di:compile
15.) bin/magento setup:static-content:deploy
16.) bin/magento indexer:reindex
17.) curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
18.) sudo apt-get install -y nodejs
19.) sudo npm install -g grunt-cli
20.) npm install
21.) grunt exec
22.) grunt less

**Comment by riconeitzel** [comment]
This one's slightly buggy in the first numbers.

Will provide an update soon!
