### ISSUE TITLE
Invalid link provided in [optional instruction]

### ISSUE THREAD

**Issue by foxer-zt** [paliarush/vagrant-magento#7]
Since master branch is unavailable, link provided in the end of optional instructions is invalid:

> 1. Use instructions provided here https://github.com/paliarush/vagrant-magento/blob/master/docs/phpstorm-configuration-windows-hosts.md

**Issue location:**
_https://github.com/paliarush/magento2-vagrant-for-developers/blob/1693ee7d14a52335fc75bdb15750601d037df088/scripts/guest/m-reinstall_

**Comment by arkadiych** [comment]
@foxer-zt , thank you fro reporting the issue. Branches "2.0" and 'develop' have been updated.
