### ISSUE TITLE
Cannot edit product from sample data

### ISSUE THREAD

**Issue by drupality** [paliarush/vagrant-magento#77]
I have install CE version with sample data by `m-switch-to-ce -f`.

Now I'm trying to edit selected product. Product name 'Driven Backpack'.
I've changed activity category for this product, clicked Save and got:

> Item (Magento\Framework\DataObject) with the same ID "16" already exists.

What am I doing wrong? Don't know how to edit product or edit of random data is impossible?

**Comment by paliarush** [comment]
@drupality it should be possible to edit any sample data items after installation. If you are still not able to do that, please report this issue at https://github.com/magento/magento2/issues since it is does not seem to be an issue related to vagrant box itself.
