### ISSUE TITLE
Only see app dir on host

### ISSUE THREAD

**Issue by createadrln** [paliarush/vagrant-magento#82]
After vagrant up when I go to the url the only thing that is there is the /app directory. During the vagrant up commands there is a notice for `chmod: cannot access ‘bin/magento’: No such file or directory`

**Comment by createadrln** [comment]
This is on Windows 10 with the latest versions of Vagrant and Virtual Box using PHP 7

**Comment by paliarush** [comment]
Looks like code base got broken for some reason. Try to recreate project from scratch or make sure that code base is uploaded from your host to guest machine (see [this page](https://github.com/paliarush/magento2-vagrant-for-developers/blob/2.0/docs/phpstorm-configuration-windows-hosts.md))
