### ISSUE TITLE
Option to specify default branches for repositories in config.yaml

### ISSUE THREAD

**Issue by jasonheecs** [paliarush/vagrant-magento#83]
Hi,

I've noticed that the default Magento 2 CE installation is version 2.2-dev as that seems to be the default branch used by the Magento 2 CE git repo. Is there a flag / switch in config.yaml to use version 2.1 during the project initialisation process?

**Comment by aarcro** [comment]
I'm trying this:

```
cd magento2ce
git checkout 2.1
```

**Comment by jasonheecs** [comment]
@aarcro yeah, that's what I was doing as well. I'm just wondering if there is an option to automate that via the config files that I missed. Seems like there is no such option though.

I made some modifications to the bash script to add such a flag for my own needs. I might make a pull request, but I'm not sure if it is appropriate, given that I assume this box is meant for development for Magento 2; not too sure how useful being able to switch to the last stable version will be.

**Comment by aarcro** [comment]
Seems reasonable that `-c` for `init_project.sh` take an optional identifier to check out.

OR Maybe add ce_branch to `repository_url` in `config.yaml` and update `init_project.sh` to use that.

Doesn't seem like you can just add `#branch` to the ce url to have it clone at that branch unfortunately.

**Comment by paliarush** [comment]
@jasonheecs thanks for proposed changes, makes sense. 

We need to make sure that it will be possible to specify branch for each of 4 currently supported repositories (CE, EE, Sample data EE and Sample data CE).

We need to find appropriate syntax for `config.yaml`, e.g. 

`ce: "git@github.com:magento/magento2.git::branchName"`

Branch name should be optional.

Would you be able to make these changes and create PR?

**Comment by jasonheecs** [comment]
@paliarush I would love to contribute to this project, but I'm swamped in work at the moment, so it could take a while. If there is still a need for this enhancement by the time I'm done, I'll submit a PR :)

**Comment by paliarush** [comment]
@jasonheecs if you find time to do it in 2 month, would be nice. After 2 month, if no PR, I will work on it. Thank you

**Comment by jasonheecs** [comment]
@paliarush Hi, made a pull request #99. Please review it :)

**Comment by paliarush** [comment]
Merged in PR #103.
