### ISSUE TITLE
Cant find 'guest' file(s)

### ISSUE THREAD

**Issue by wpoortman** [paliarush/vagrant-magento#88]
When I use the bash init_proces.sh, the command line returns a error which results in a invalid Vagrant installation process.

`bash: /vagrant/scripts/guest/m-clear-cache: No such file or directory`
_This error comes up after 'Unlinking CE sample data'_

Two weeks ago, it all worked perfectly on my local machine.

**Comment by paliarush** [comment]
Looks like Vagrant is unable to mount shared folders for some reason. Possibly you have broken NFS server configuration on your host (if your host is OSX or Linux).

Have you tried the following item from FAQ to get more info?

> To debug any CLI script in current Vagrant project, set debug:vagrant_project option in config.yaml to 1

**Comment by Ramboz89** [comment]
Hello guys, I have got the same problem, I'm on macOs and I've just upgraded to Sierra, could it be the issue? 

However on my personal laptop is working just fine.

**Comment by paliarush** [comment]
@Ramboz89 Can you please make sure that shared folders and NFS-shares were mounted (after `vagrant ssh` there should be project at the same path as on your host)? I'm on Yosemite and haven't  encountered such issue.

**Comment by cgaubuchon** [comment]
Yup, having the same issue after upgrading to MacOS Sierra. Seems that any/all of my projects that use NFS-shares are no longer sharing the folders as expected. I enabled `debug:vagrant_project` and took a look but there isn't anything that seems to specifically point to this being the issue. Going to search around since this seems to be a Vagrant issue more than an issue with this specific repo.

**Comment by cgaubuchon** [comment]
Figured it out in my case. I opened the VirtualBox GUI client and noticed that there were two instances of "vagrant-magento" VMs running. Since I didn't have any critical data I stopped and removed them entirely and ran the `init_process.sh` script again and everything worked.

**Comment by rhssk** [comment]
I'm on Linux system and I'm getting `bash: /vagrant/scripts/guest/m-clear-cache: No such file or directory` error after `Unlinking CE sample data` as well. NFS is at default configuration. I can SSH in Vagrant box but there are no shared folders mounted.

Here's a debug dump:
https://gist.github.com/rhssk/f32fbf555cb65176029af609f51c7fb0

**Comment by paliarush** [comment]
@cgaubuchon Thanks for investigating that.

@rhssk I can see in [logs](https://gist.github.com/rhssk/f32fbf555cb65176029af609f51c7fb0#file-magento2-vagrant-for-developers-debug-dump-L2485) that Vagrant failed to mount shared folders in your case. Looks like some incompatibility of Vagrant+VirtualBox+NFS+YourOS. If you cannot make NFS work, it is possible to set [use_nfs](https://github.com/paliarush/magento2-vagrant-for-developers/blob/2.0/etc/config.yaml.dist#L28) option to 0, then you will basically have the same experience as guys whose host OS is Windows (which does not support NFS).

**Comment by rhssk** [comment]
@paliarush That's a shame, haven't had any issues when working with NFS alone. Any guess what causes the `[Unknown source file]` error? From the log it seems unrelated to NFS issues.

**Comment by paliarush** [comment]
@rhssk I can see in log the following:

> ==> magento2.vagrant243: Mounting NFS shared folders...
> [2016-10-18 20:12:00] 
> The following SSH command responded with a non-zero exit status.
> Vagrant assumes that this means the command failed!

Have you tried to create simple Vagrantfile which will mount NFS folders on your environment? Something like this should work (then just do `vagrant up`):

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API_VERSION = 2
Vagrant.configure(VAGRANT_API_VERSION) do |config|
    config.vm.box = "ubuntu/trusty64"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.name = "magento2.ubuntu-14.04"
    end

    config.vm.synced_folder '.', '/var/www/test', type: "nfs", create: true

end
```

**Comment by rhssk** [comment]
That results in 
<pre><code>The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

set -e
mkdir -p /var/www/test
mount -o vers=3,udp 192.168.11.1:/home/user/test/var/www/test
if command -v /sbin/init && /sbin/init --version | grep upstart; then
  /sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT=/var/www/test
fi

Stdout from the command:

Stderr from the command:

stdin: is not a tty
mount.nfs: Connection timed out</pre></code>

I'll have to troubleshoot this further, but at the moment it indeed seems unrelated to your work. Will post a solution to my problem if I find it.

**Comment by rhssk** [comment]
In my case ufw was the reason why nfs timed out.

**Comment by paliarush** [comment]
@rhssk Thanks for checking. I'll improve error reporting for the case when NFS cannot be mounted, to avoid any confusion in the future.

**Comment by jthn** [comment]
In case anyone else happens across this thread.  I'm running Ubuntu with an encrypted home directory, and was getting this same error.  Moving the vagrant project out of my home directory allowed me to complete the installation successfully.
