### ISSUE TITLE
Enable Mail Support

### ISSUE THREAD

**Issue by paliarush** [paliarush/vagrant-magento#9]
There should be possibility to read Emails sent by Magento. Ideally we should put every email to some directory visible from the host, so it can be opened using host email client (e.g. Outlook).

**Comment by paliarush** [comment]
Merged in scope of #39

**Comment by BaDos** [comment]
How about sending emails to the real address?
Could I send emails to the real address?
Thanks.

**Comment by paliarush** [comment]
@BaDos it was not planned, but you can contribute alternative solution based on "postfix". Then we need to have some switch in config.yaml to choose between logging to file and sending to real addresses.
