### ISSUE TITLE
ERROR 1146 (42S02) at line 1: Table 'magento.core_config_data' doesn't exist 

### ISSUE THREAD

**Issue by apothegm** [paliarush/vagrant-magento#91]
I've tried getting this up and running a variety of different ways on a Windows host. Updating all my dependencies and using cmder bash and git bash. But I always get this: `ERROR 1146 (42S02) at line 1: Table 'magento.core_config_data' doesn't exist`

Database gets created, but no tables exist.

Vagrant box goes up but when I visit frontend or backend, I get:

```
Autoload error
Vendor autoload is not found. Please run 'composer install' under application root directory.
```

```
$ vagrant version
Installed Version: 1.8.6

$ php --version
PHP 5.6.8 (cli) (built: Apr 15 2015 15:07:09)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans

$ composer --version
Composer version 1.3-dev (23d2e5600a91746fe4c2e19621431eeac21f174e) 2016-10-04 10:20:39

$ git --version
git version 2.10.1.windows.1

```

**Comment by paliarush** [comment]
This happens because Magento installation fails and database is not populated (should happen [here](https://github.com/paliarush/magento2-vagrant-for-developers/blob/2.0/scripts/guest/m-reinstall#L84)). To understand why this happens, please try to enable debug mode to get more details (see item 1 in [FAQ](https://github.com/paliarush/magento2-vagrant-for-developers#faq)).

Also try to run `bash ./init_project -fcp` from git bash (this will re-create everything from scratch using your current config.yaml).

**Comment by paliarush** [comment]
@apothegm please reopen if you were unable to resolve the issue

**Comment by paliarush** [comment]
@apothegm I was able to reproduce your issue when checked out Magento codebase manually, but didn't do `composer install` in the root of Magento project. This was not expected flow, but after latest changes even this flow should work. Please let me know if you still experience any issues.

**Comment by valoujjal** [comment]
Hi, i'm new to magento i'm trying follow your instruction to install magento through vagrant box. but each time i install magento without sample data it works fine but whenever i try to install sample data it stops working says some a:4:{i:0;s:105:"SQLSTATE[HY000] [2002] errors... then i tried to implement this solution vagrant ssh and run sudo dpkg-reconfigure mysql-server-5.6, sudo service mysql restart but that is also not in work. after sometimes it stops showing errors and stops loading magento. then i think i have to work or learn magento without sample data i restart everything from beginning but it works fine sometime...... but again it stops working after 10 minutes without showing any errors saying server not found..... and magento loads only in mozilla firefox not in google crome says proxy error......

then i try to second instance from the beginning it shows same as the above...
ERROR 1146 (42S02) at line 1: Table 'magento.core_config_data' doesn't exist  

i'm working in windows10

**Comment by paliarush** [comment]
@valoujjal have you tried to enable debug mode by setting `debug:vagrant_project` option in config.yaml to 1? This should give you the maximum output. Regarding different browsers, there may be duplicate records pointing to different servers in `hosts` file on your Windows10. 

Does it work for you without sample data?

Sorry for late response.
