### ISSUE TITLE
vagrant-magento/scripts/output_functions.sh: line 168: syntax error near unexpected token `>'

### ISSUE THREAD

**Issue by kvodenicharov** [paliarush/vagrant-magento#93]
When running bash init_project.sh on windows 10 I get the following error:

vagrant-magento/scripts/output_functions.sh: line 168: syntax error near unexpected token `>'

**Comment by paliarush** [comment]
Please make sure that you are running `bash init_project.sh` in GitBash v2.7+, not in native Windows command prompt. Works for me on Windows 10, with git version `2.9.3.windows.1`. If does not work for you in git v2.7+, please provide your version.

**Comment by kvodenicharov** [comment]
I couldn't get it to work with an older version of gitbash, thus I updated to 2.10.1.windows.1. However it didn't work again. 
After enabling bash on ubuntu on my windows 10 however, the setup went fine. Lets consider this issue closed.
