### ISSUE TITLE
Error running bash init_project.sh

### ISSUE THREAD

**Issue by dazuaz** [paliarush/vagrant-magento#97]
Had to do:

`composer clear-cache` , most likely because i had previously cloned/installed 

Also had to delete entry from /etc/exports due to and NFS error, prolly related to the error I ran into before clearing the composer cache.

Thanks for the project.

**Comment by paliarush** [comment]
@dazuaz do you mean that you tried to run `ini_project.sh` twice? If so, this is not expected scenario. If you need to recreate project, use `init_project.sh -f` or `init_project.sh -fc` (see readme for details).

If you were trying to install project from scratch, please let me know your OS version and the latest commit in `magento2-vagrant-for-developers` repository you have.

Thanks
